### ISSUE TITLE
[please fix] MetalChests Upgrades crash you

### ISSUE THREAD

**Issue by iamweirdie** [T145/metalchests#100]
When a player tries to pick up a MetalChest upgrade from the ground, the player gets kicked and will

To Reproduce

Find a dropped MetalChest upgrade
Try to pick it up
Proceed to yell at your computer as you get kicked
Try to login within the radius of the upgrade, keep getting kicked
Versions:

Minecraft: 1.12.2
Forge: 14.23.5.2838
Mod Pack : World of Dragons v. 18.5.215
Mod Name: MetalChests
Mod Version: 5.8.9
Crash Report: https://paste.ubuntu.com/p/vc648MXV4D/

**Comment by T145** [comment]
```
Caused by: java.lang.NullPointerException
    at electroblob.wizardry.WizardData.get(WizardData.java:462)
    at electroblob.wizardry.client.ClientProxy.handlePlayerSyncPacket(ClientProxy.java:458)
    at electroblob.wizardry.packet.PacketPlayerSync$1.run(PacketPlayerSync.java:30)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
```
Doesn't look like an issue w/ my mod.
